service: flowaccount-sdk
frameworkVersion: '>=1.1.0'
plugins:
  - serverless-offline
package:
  individually: true
  excludeDevDependencies: false
provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  environment:
    FLOWACCOUNT_API_ENDPOINT: ${env:FLOWACCOUNT_API_ENDPOINT}
    CLIENT_GRANT_TYPE: ${env:client_credentials}
    CLIENT_SCOPE: ${env:CLIENT_SCOPE}
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
functions:
  create-cash-invoice:
    handler: src/handler.createCashInvoice
    events:
      - http:
          path: cash-invoice
          method: post
  webhook:
    handler: src/handler.webhook
    events:
      - http:
          path: webhook
          method: post
  subscribe-page365:
    handler: src/handler.subscribe
    events:
      - http:
          path: subscribe
          method: post